class DamageKickHandler : EventHandler
{
    override void WorldThingDamaged(WorldEvent e)
    {
        if (!(e.thing is "QuakePlayer")) return;

        let mo = QuakePlayer(e.thing);

        mo.damageTics = 0;

        double scale = 40.0 / mo.health;
        double kick = Clamp(e.damage * scale, 5, 10);

        if (e.inflictor)
        {

        }
        else    // Environmental damage
        {
            mo.damageRoll = 0;
            mo.damagePitch = -kick;
        }
    }
}