version "3.7.2"

#include "zscript/quake_move/quake_player.zc"
#include "zscript/quake_move/footstep.zc"
#include "zscript/quake_move/kicker.zc"
#include "zscript/quake_move/damage_kick_handler.zc"
#include "zscript/quake_move/land_kick_handler.zc"
#include "zscript/quake_move/weapon_lag_handler.zc"
#include "zscript/quake_move/speedometer_handler.zc"
#include "zscript/quake_move/strafejump_handler.zc"